project: CTDS models for discrete-space deep dives

defaults:
  data: zc84
  subset: all_dives
  validation: no_validation
  observation_model: uniform_systematic
  priors: standard_priors
  sampler: test

base_paths: # main output directory to save fits and figures from model runs
  fit: output

sub_paths: # created under the output directory for each model run
  figures: figures
  posterior_predictions: posterior_predictions
  prior_predictions: prior_predictions
  comparisons: comparisons
  dives: dives
  posteriors: posteriors
  imputations: imputations

base_names: # files containing analysis artifacts/output
  fit: sampler_trace.RData  # MCMC chain from gibbs sampler over model params.
  fit_inds: fit_inds.RData  # indices that partition data into test/train sets
  stage_priors: stage_priors.RData # parameters for stage transition time priors
  ctmc_priors: ctmc_priors.RData # parameters for CTMC priors
  posterior_predictions:
    file: samples_X.RData   # posterior predictive distribution draws
    index_pattern: X        # character to replace with sample indices
  prior_predictions:
    file: samples_X.RData   # prior predictive distribution draws
    index_pattern: X        # character to replace with sample indices
