#!/bin/bash

# set working directory
cd `dirname "${BASH_SOURCE[0]}"`
cd ../..

rsync -r jmh182@dcc-slogin.oit.duke.edu:/hpc/group/gelfandlab/jmh_scratch/analysis/*.Rout ./
rsync -r jmh182@dcc-slogin.oit.duke.edu:/hpc/group/gelfandlab/jmh_scratch/analysis/output ./
